server:
    port: 9777 #启动端口
spring:
    application:
        name: smart-auth
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
        serialization:
          INDENT_OUTPUT: true
    redis:
        database: 1
        host: ${REDIS_HOST:47.75.36.103}
        port: ${REDIS_PORT:6379}
        pool:
        max-active: 20
        password: ${REDIS_PASSWORD:123456}
    cache:
        type: redis
        cache-names: userdetail,cache1
        redis:
          cache-null-values: true
          key-prefix: userdetail_
          time-to-live: 0ms
          use-key-prefix: true
    jpa:
        hibernate:
          ddl-auto: none
        show-sql: true
        properties:
          hibernate:
            dialect: com.julong.cloud.smartcommon.jdbc.MySQL5DialectUTF8
        database: mysql
    datasource:
          name: test
          url: jdbc:mysql://${MYSQL_HOST:47.75.36.103}:${MYSQL_PORT:3333}/test?useUnicode=true&characterEncoding=UTF8
          username: db_test
          password: db_test
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
    rabbitmq:
      host: ${RABBIT_MQ_HOST:47.75.36.103}
      port:  ${RABBIT_MQ_PORT:5672}
      username: ljl
      password: 123456
    sleuth:
      enabled: true
      http:
        legacy:
          enabled: true


feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
    instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
        # docker 部署开启
        prefer-ip-address: true
        ip-address: 127.0.0.1
    client:
        serviceUrl:
                    # docker 部署开启
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate: error
    com.julong.cloud: debug


