spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:47.75.36.103}:${MYSQL_PORT:3333}/cloud_zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: db_test
    password: db_test
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
  application:
    name: smart-trace
   #zipkin数据保存到数据库中需要进行如下配置
   #表示当前程序不使用sleuth
  sleuth:
    enabled: false
   #表示zipkin数据存储方式是mysql

zipkin:
  storage:
    type: mysql
  collector:
    rabbitmq:
      addresses: ${RABBIT_MQ_HOST:47.75.36.103}
      port: ${RABBIT_MQ_PORT:5672}
      password: 123456
      username: ljl
      queue: zipkin
server:
  port: 9411

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://${EUREKA_HOST:47.75.36.103}:${EUREKA_PORT:8761}/eureka/
