eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
spring:
  application:
    name: smart-gate
zuul:
  ignoredServices: '*'
  routes:
    api:
      path: /admin/**
      serviceId: smart-admin
    auth:
      path: /auth/**
      serviceId: smart-auth