eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
server:
  port: 8888
spring:
  application:
    name: smart-gate
  rabbitmq:
    host: ${RABBIT_MQ_HOST:47.75.36.103}
    port:  ${RABBIT_MQ_PORT:5672}
    username: ljl
    password: 123456
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
zuul:
  sensitive-headers:
  add-host-header: true
  ignoredServices: '*'
  routes:
    api:
      path: /admin/**
      serviceId: smart-admin
    auth:
      path: /auth/**
      serviceId: smart-auth
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
  httpclient:
    enabled: false
  okhttp:
    enabled: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
          strategy: SEMAPHORE